"""update

Revision ID: 164e0da95f68
Revises: 497179c940f7
Create Date: 2019-05-29 15:26:16.480636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164e0da95f68'
down_revision = '497179c940f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_member_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_member_group')
    # ### end Alembic commands ###
